name: try file.txt within github_output

on: push

jobs:
  github_output:
    runs-on: ubuntu-latest
    steps:
      - name: write something into output-file
        id: output_str
        run:
          echo str='Lets output it!' | tee $GITHUB_OUTPUT
      - name: get it again
        run:
          echo ${{ steps.output_str.outputs.str }}


