name: hadolint multi file

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        # continue-on-error: true
        with:
          dockerfile: Dockerfile*
          recursive: true
          format: sarif
          output-file: hadolint-result.sarif
          # no-fail: true
      - name: Upload result to Github Security
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-result.sarif