name: hadolint multi file

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: hadolint/hadolint-action@v2.1.0
      with:
        args: Dockerfile
    - uses: actions/upload-artifact@v2
      with:
        name: lint-results
        path: .