name: Hadolint container multi file

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hadolint/hadolint

    steps:
      - name: lint
        run:
          hadolint Dockerfile