name: hadolint multi file

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Hadolint
        uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile*
          recursive: true
          format: sarif
          output-file: hadolint-result.sarif
    # - uses: actions/upload-artifact@v2
    #   with:
    #     name: lint-results
    #     path: .
      - name: Upload result to Github Securities
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-result.sarif