name: Hadolint container multi file

on: push

jobs:
  hadolint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/hadolint/hadolint:v2.12.0-debian
      # volumes:
      #   - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: lint
        run: |
          bash -c "shopt -s globstar"
          run: find . -name "Dockerfile*" -exec hadolint {} +